run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/flavono123/kupid

issues:
  exclude-dirs:
    - cmd/gui
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
