before:
  hooks:
    - go mod download
builds:
  - binary: kupid
    main: ./cmd/kupid/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "8"
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w

krews:
  - name: pickdeep
    ids:
      - krew
    commit_msg_template: "Krew plugin update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/flavono123/kupid"
    description: |-
      Pick any Deep schema fields, create your own table view of Kubernetes TUI.
    repository:
      owner: flavono123
      name: flew
      branch: main

archives:
  - id: krew
    format: tar.gz
    name_template: |-
      pickdeep_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    format_overrides:
      - goos: windows
        format: zip
  - format: tar.gz
    name_template: |-
      kupid_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
