before:
  hooks:
    - go mod download
builds:
  - binary: kupid
    main: ./cmd/kupid/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "8"
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: |-
      kupid_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
