// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectToContexts(arg1:Array<string>):Promise<Array<main.ContextConnectionResult>>;

export function GetCurrentContext():Promise<string>;

export function GetGVKs(arg1:Array<string>):Promise<Array<main.MultiClusterGVK>>;

export function GetNodeTree(arg1:main.MultiClusterGVK,arg2:Array<string>):Promise<Array<main.TreeNode>>;

export function GetResources(arg1:main.MultiClusterGVK,arg2:Array<string>):Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function ListContexts():Promise<Array<string>>;

export function RefreshContexts():Promise<Array<string>>;
