// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToContexts(arg1) {
  return window['go']['main']['App']['ConnectToContexts'](arg1);
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetGVKs(arg1) {
  return window['go']['main']['App']['GetGVKs'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListContexts() {
  return window['go']['main']['App']['ListContexts']();
}

export function RefreshContexts() {
  return window['go']['main']['App']['RefreshContexts']();
}
