// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectToContexts(arg1:Array<string>):Promise<Array<main.ContextConnectionResult>>;

export function GetCurrentContext():Promise<string>;

export function GetResourcesForContexts(arg1:Array<string>):Promise<Array<main.ResourceInfo>>;

export function Greet(arg1:string):Promise<string>;

export function ListContexts():Promise<Array<string>>;
