// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToContexts(arg1) {
  return window['go']['main']['App']['ConnectToContexts'](arg1);
}

export function DeleteFavoriteView(arg1) {
  return window['go']['main']['App']['DeleteFavoriteView'](arg1);
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetFavoriteViewsForGVK(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFavoriteViewsForGVK'](arg1, arg2, arg3);
}

export function GetGVKs(arg1) {
  return window['go']['main']['App']['GetGVKs'](arg1);
}

export function GetNodeTree(arg1, arg2) {
  return window['go']['main']['App']['GetNodeTree'](arg1, arg2);
}

export function GetResources(arg1, arg2) {
  return window['go']['main']['App']['GetResources'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListContexts() {
  return window['go']['main']['App']['ListContexts']();
}

export function ListFavoriteViews() {
  return window['go']['main']['App']['ListFavoriteViews']();
}

export function RefreshContexts() {
  return window['go']['main']['App']['RefreshContexts']();
}

export function RenameFavoriteView(arg1, arg2) {
  return window['go']['main']['App']['RenameFavoriteView'](arg1, arg2);
}

export function SaveFavoriteView(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveFavoriteView'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function StartWatch(arg1, arg2) {
  return window['go']['main']['App']['StartWatch'](arg1, arg2);
}

export function StopWatch() {
  return window['go']['main']['App']['StopWatch']();
}
