name: Bump

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

# TODO: set pr branch name pattern as release/${version}
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          changelog-notes: |
            # Changelog

            ## 0.0.1 (2025-01-01)

            ### Features & Bug Fixes

            on the alpha stage would not be specified in detail
            maybe commits are also squashed in later.
